---
- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - include: tasks/apache.yml
    - name: install lamp stack programs
      apt: name={{item}} state=present
      with_items:
        - mysql-server
        - php5
